### ISSUE TITLE
Use static SFmpq in MinGW

### ISSUE THREAD

**Issue by jjf28** [jjf28/Chkdraft#76]
A static version of SFmpq should be used for the MinGW compile rather than the dynamic version to maximize simplicity for end-users.

**Comment by xboi209** [comment]
What's difficult with compiling the dynamic version?

**Comment by jjf28** [comment]
Shouldn't be that difficult to compile; but to run you have to keep the dll together with Chkdraft or in OS-dependent locations if it was compiled as dynamic.

**Comment by xboi209** [comment]
Well that's pretty standard to have a dll in the same folder as Chkdraft.

**Comment by jjf28** [comment]
Hmm? Has been a lone-executable for quite some time

**Comment by xboi209** [comment]
I mean to have a dll in the same folder as an exe, not Chkdraft in general.

**Comment by jjf28** [comment]
I typically prefer my programs to operate as standalone executables, suppose since adding the chkd directory it's not as such anymore, but I do like the style.
